---
title: "4Mel.2Lung.NeoTIL combined alluvial plot for clonetype evolution from 5 timepoints of bulkTCR - 20230605"
author: "Quy Ai Ngo"
date: "05-Jun-2023"
output: slides_presentation
---

```{r setup, echo = FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
setwd("/home/localadmin/Desktop/RESEARCH/MArnaud/bulk_TCR/Clone_evolution/MelLungNeoTIL/20230605")
```

## 1. Load libraries
```{r load libraries}

library(tidyverse)
library(data.table)
library(ggplot2)
library(ggalluvial)
library(randomcoloR)
library(ggforce)
library(scales)
library(grid)
library(ggpubr)
library(cowplot)
#library(kableExtra)

```


```{r patient & sample info}

# patients <- c("14MH", "13LN", "13P4", "1IJX", "1EDA", "1HU3", "0ZMN", "1I3M", "1FUI", "1IKA")
sample.5f <- c("B0", "T0", "ACTP", "B30", "T30") # for patient1,7,2,14
patient1 <- "14MH"
patient2 <- "13P4"
patient14 <- "1E18"

sample.6fT30 <- c("B0", "T0", "ACTP", "B30", "T30.A", "T30.B")
patient7 <- "13LN" #patient7b (B0 & T0 ATATIL)

sample.6fT0 <- c("B0", "T0.A", "T0.B", "ACTP", "B30", "T30") # for patient3,5
patient3 <- "1EDA" 
patient5 <- "1HU3"

nMel = 4 # 4 patients
nLung = 2 # 2 patients

```


# 1. Load data
```{r data import & cleaning}

mainDir <- "/home/localadmin/Desktop/RESEARCH/MArnaud/bulk_TCR/"

# Get a list of all files named per patient by sample key words:
getFiles <- function(patient, TCRdir) {
  filenames <- c()
  for (f in  c("B0", "T0", "ACTP", "B30", "T30")) {
    spl <- list.files(paste0(mainDir, patient, TCRdir),
                      pattern = f, full.names=TRUE)
    filenames <- c(filenames, spl)
  }
  print(filenames)
  listDF <- lapply(filenames, data.table::fread)
  listDF <- lapply(listDF, subset, Frame == "IN" & Count > 1)
  return(listDF)
}

listDF1 <- getFiles(patient1, "/TCR_repertoire")
listDF7 <- getFiles(patient7, "/TCR_repertoire/For_clone_origins4") # B0 & T0 from ATATIL
listDF2 <- getFiles(patient2, "/TCR_repertoire")
listDF14 <- getFiles(patient14, "/TCR_repertoire")

listDF3 <- getFiles(patient3, "/TCR_repertoire")
listDF5 <- getFiles(patient5, "/TCR_repertoire")

# name listDF
names(listDF1) <- sample.5f
names(listDF2) <- sample.5f
names(listDF14) <- sample.5f

names(listDF7) <- sample.6fT30

names(listDF3) <- sample.6fT0
names(listDF5) <- sample.6fT0

```


# 2. Clean up & prepare data for alluvia
```{r prepare list of df for ggalluvial}

# 1. add "Clonotype" column to each df of the list.DF by combining TRBV, CDR3_aaseq and TRBJ
# 2. add "Status" column ("present" & "absent") to each df, according to the read counts
# 3. add "Freq" column to each df for clone Frequency in each sample
# 4. select 4 columns Clonotype, Count, Freq, Status & add patient name to Clonotype
# 5. Reorder list.DF & rename files in list

prep_df_alv <- function(spl, patient){
  spl <- spl %>%
    unite("Clonotype", c(TRBV, CDR3_aaseq, TRBJ), remove = F) %>% #1
    mutate(Status = ifelse(Count > 1, "P", "A")) %>% #2
    mutate(Freq = 100*(round(Count / sum(Count), 10))) %>% #3, round up decimal to 10 digits
    select(Clonotype, Count, Freq, Status) %>% #4
    mutate(Clonotype = paste(patient, Clonotype, sep = "_"))
}
listDF1 <- lapply(listDF1, prep_df_alv, patient1)
listDF7 <- lapply(listDF7, prep_df_alv, patient7)
listDF2 <- lapply(listDF2, prep_df_alv, patient2)
listDF14 <- lapply(listDF14, prep_df_alv, patient14)
listDF3 <- lapply(listDF3, prep_df_alv, patient3)
listDF5 <- lapply(listDF5, prep_df_alv, patient5)

# IN ADDITION:
# For patient7: combine 2 T30 samples into 1, normalize Freq & Count of each Clonotype by dividing them by 2
CombineT30 <- function(listDF) {
  DF.T30 <- rbind(listDF$T30.A, listDF$T30.B) %>%
    mutate(Freq = Freq/2) %>% 
    mutate(Count = Count/2) %>% 
    group_by(Clonotype, Status, .drop = F) %>% 
    summarise(Count = sum(Count),
              Freq = sum(Freq)) %>% 
    select(Clonotype, Count, Freq, Status) %>% 
    as.data.frame()

  listDF <- list(listDF$B0, listDF$T0, listDF$ACTP, listDF$B30, DF.T30)
  names(listDF) <- sample.5f
  return(listDF)
  
  rm(DF.T30)
}
listDF7 <- CombineT30(listDF7)

# For patient 3 & 5: Combine 2 T0 samples into 1, normalize Freq and Count of each Clonotype by dividing them by 2
CombineT0 <- function(listDF) {
  DF.T0 <- rbind(listDF$T0.A, listDF$T0.B) %>%
    mutate(Freq = Freq/2) %>% 
    mutate(Count = Count/2) %>% 
    group_by(Clonotype, Status, .drop = F) %>% 
    summarise(Count = sum(Count),
              Freq = sum(Freq)) %>% 
    select(Clonotype, Count, Freq, Status) %>% 
    as.data.frame()

listDF <- list(listDF$B0, DF.T0, listDF$ACTP, listDF$B30, listDF$T30)
names(listDF) <- sample.5f
return(listDF)

rm(DF.T0)
}
listDF3 <- CombineT0(listDF3)
listDF5 <- CombineT0(listDF5)

```


```{r create sample suffixes for joined df of patient with even-number of samples}

# Combine samples from all patients (B0 of pt1,pt2,pt3; T0 of pt1,pt2,pt3, etc.)
# Mel
combineSpl.Mel <- function(i) {
  i <- rbind(listDF1[[i]], listDF7[[i]], listDF2[[i]], listDF14[[i]]) %>% 
    mutate(Freq = Freq/nMel) %>% 
    mutate(Count = Count/nMel)
}
B0.M <- combineSpl.Mel("B0")
T0.M <- combineSpl.Mel("T0")
ACTP.M <- combineSpl.Mel("ACTP")
B30.M <- combineSpl.Mel("B30")
T30.M <- combineSpl.Mel("T30")
listDF.Mel <- list(B0.M, T0.M, ACTP.M, B30.M, T30.M)
names(listDF.Mel) <- sample.5f

# Lung
combineSpl.Lung <- function(i) {
  i <- rbind(listDF3[[i]], listDF5[[i]]) %>% 
  mutate(Freq = Freq/nLung) %>% 
  mutate(Count = Count/nLung)
}
B0.L <- combineSpl.Lung("B0")
T0.L <- combineSpl.Lung("T0")
ACTP.L <- combineSpl.Lung("ACTP")
B30.L <- combineSpl.Lung("B30")
T30.L <- combineSpl.Lung("T30")
listDF.Lung <- list(B0.L, T0.L, ACTP.L, B30.L, T30.L)
names(listDF.Lung) <- sample.5f

rm(B0.M, T0.M, ACTP.M, B30.M, T30.M, B0.L, T0.L, ACTP.L, B30.L, T30.L); invisible(gc()); gc()

```


```{r join all df in the list.DF into 1 big df of TCR repertoire with 2 statuses, clone Frequency}

sfx.5f <- c("_B0", "_T0", "_ACTP", "_B30", "_T30")

# 6. avoid automatic dplyr column renaming when joining all df
# 7. convert Status: NA into "A"
# 8. convert Freq: NA into artificial 0
# 9. select relevant columns
# 10. add Status combinations for each clone

# Join 5 samples :
joinDF.5f <- function(listDF) {
  res <- listDF[[1]]
  for(i in seq(1, (length(listDF) - 1), by = 1)) {
    res <- merge(res, listDF[[i+1]], all = TRUE,
                 suffixes = sfx.5f[i:(i+1)], by = "Clonotype") 
  }
  data.table::setnames(res, old = c("Count", "Freq", "Status"), new = c("Count_T30", "Freq_T30", "Status_T30")) #6
  return(res)
}
ResMel <- joinDF.5f(listDF.Mel)
ResLung <- joinDF.5f(listDF.Lung)

```


```{r add dummy frequency & clone status}

# Add dummy frequency for all patients:
addFreqStatus <- function(res) {
  res <- res %>%
  mutate(across(starts_with("Status"), ~ifelse(is.na(.x),"A",.x))) %>% #7
  mutate(across(starts_with("Freq"), 
                ~ifelse(is.na(.x), (round(0/100,10)), .x))) %>% #8 dummy values used for calculation of 0-read clones
  select(Clonotype, starts_with("Freq"), starts_with("Status")) #9
}
ResMel <- addFreqStatus(ResMel)
ResLung <- addFreqStatus(ResLung)

```


```{r add cloneID}

# Add cloneID as clone status combination - 5 samples:
addCloneID.5f <- function(res) {
  res <- mutate(res, 
                cloneID = paste(res$Status_B0, res$Status_T0, res$Status_ACTP, res$Status_B30, res$Status_T30, sep="_")) #10
}
ResMel <- addCloneID.5f(ResMel)
ResLung <- addCloneID.5f(ResLung)

```


```{r prepare alv format}

# Summarize 5 samples:
summarise.5f <- function(res) {
  res <- res %>% 
  group_by(cloneID) %>%
  summarise(Freq_B0 = sum(Freq_B0),
            Freq_T0 = sum(Freq_T0),
            Freq_ACTP = sum(Freq_ACTP),
            Freq_B30 = sum(Freq_B30),
            Freq_T30 = sum(Freq_T30)
           ) %>% 
  arrange(cloneID)
  names(res) <- sub("Freq_*", "", names(res))
  return(res)
}
ResMel <- summarise.5f(ResMel)
ResLung <- summarise.5f(ResLung)

#write.table(ResMel, "ResMel_clone.evolution_freq_of_cloneIDs_20230605.txt", append = F, quote = F, sep = "\t", row.names = F, col.names = T)
#write.table(ResLung, "ResLung_clone.evolution_freq_of_cloneIDs_20230605.txt", append = F, quote = F, sep = "\t", row.names = F, col.names = T)

```


```{r transform alv to long format}

# Convert res to long alv format:
toAlv <- function(res) {
  alv <- res %>%
  gather(key = Sample, value = Freq, 
         2:length(res), 
         factor_key = TRUE) %>% 
  mutate(Status = ifelse(Freq > 0, "present", "absent"))
  is_alluvia_form(alv, 2:length(alv))
  return(alv)
}
AlvMel <- toAlv(ResMel)
AlvLung <- toAlv(ResLung)

AlvMel %>% group_by(Sample) %>%  summarise(freq = sum(Freq)) #sanity check
AlvLung %>% group_by(Sample) %>%  summarise(freq = sum(Freq)) #sanity check

```


```{r finish alv df}

## cloneOri categories defined below is the same for all patients:
cloneOri <- c("BT.ori_B.persist_T.infiltr",  "T.ori_B.persist_T.infiltr",
              "B.ori_B.persist_T.infiltr", "NA.ori_B.persist_T.infiltr",
              "BT.ori_B.persist_T.noninfiltr", "T.ori_B.persist_T.noninfiltr", 
              "BT.ori_B.nonpersist_T.infiltr", "T.ori_B.nonpersist_T.infiltr",
              "BT.ori_B.nonpersist_T.noninfiltr", "T.ori_B.nonpersist_T.noninfiltr",
              "others") #alluvium color categories

# Add clone origin - 5 samples:
addCloneOri.5f <- function(alv) {
  alv <- alv %>% 
    mutate(cloneOri = ifelse(cloneID == "P_P_P_P_P", "BT.ori_B.persist_T.infiltr", #"light red",
                      ifelse(cloneID == "A_P_P_P_P", "T.ori_B.persist_T.infiltr", #"dark red",
                      ifelse(cloneID == "P_A_P_P_P", "B.ori_B.persist_T.infiltr", #"light green",
                      ifelse(cloneID == "A_A_P_P_P", "NA.ori_B.persist_T.infiltr", #"dark green",
                      ifelse(cloneID == "P_P_P_P_A", "BT.ori_B.persist_T.noninfiltr", #"light orange",
                      ifelse(cloneID == "A_P_P_P_A", "T.ori_B.persist_T.noninfiltr", #"brown", 
                      ifelse(cloneID == "P_P_P_A_P", "BT.ori_B.nonpersist_T.infiltr", #"light purple",
                      ifelse(cloneID == "A_P_P_A_P", "T.ori_B.nonpersist_T.infiltr", #"dark purple",
                      ifelse(cloneID == "P_P_P_A_A", "BT.ori_B.nonpersist_T.noninfiltr", #"light blue",
                      ifelse(cloneID == "A_P_P_A_A", "T.ori_B.nonpersist_T.noninfiltr", #"teal",
                      "others" #"grey")
                      ))))))))))) #alluvium legend
  alv$cloneOri <- factor(alv$cloneOri, levels = cloneOri) #alluvium color categories
  return(alv)
}
AlvMel <- addCloneOri.5f(AlvMel)
AlvLung <- addCloneOri.5f(AlvLung)

# Factorize Sample for all patients:
AlvMel$Sample <- factor(AlvMel$Sample, levels = sample.5f)
AlvLung$Sample <- factor(AlvLung$Sample, levels = sample.5f)

# Factorize other variables for all patients:
factorizeOthers <- function(alv) {
  alv$cloneID <- factor(alv$cloneID, levels = unique(alv$cloneID)) #alluvium
  alv$Status <- factor(alv$Status, levels = c("present", "absent")) #stratum
  alv$stratum_text <- as.character(alv$Status) #stratum_text
  return(alv)
}
AlvMel <- factorizeOthers(AlvMel)
AlvLung <- factorizeOthers(AlvLung)

# Save alv df of combined patients:
write.table(AlvMel, paste0("4MelNeoTIL_bulkTCR_frequency.status_of_clone.evolution_from.5.timepoints_for_alluvial.plot_20230605.txt"),
            sep = "\t", append = F, quote = F, row.names = F, col.names = T)  
write.table(AlvLung, paste0("2LungNeoTIL_bulkTCR_frequency.status_of_clone.evolution_from.5.timepoints_for_alluvial.plot_20230605.txt"),
            sep = "\t", append = F, quote = F, row.names = F, col.names = T)  

```


# 3. Plot
```{r prepare artificial scale for "absent" stratum}

#fraction_missing1 <- 15 # Quy's 1read.Scheme
fraction_missing <- 25

addAbsentFreq <- function(sampleList, alv) {
  for (spl in sampleList){
  mask_missing <- (alv$Sample == spl) & (alv$Status == "absent")
  alv[mask_missing, ]$Freq <- fraction_missing/sum(mask_missing)
  }
  return((alv))
}
AlvMel <- addAbsentFreq(sample.5f, AlvMel)
AlvLung <- addAbsentFreq(sample.5f, AlvLung)

# Sanity check for total frequency, including absent frequency, per sample:
AlvMel %>% group_by(Sample) %>% summarise(freq = sum(Freq))
AlvLung %>% group_by(Sample) %>% summarise(freq = sum(Freq))

```


```{r set axis labels, legend title & breaks}

# Get new y axis breaks and labels for true scale of "present" stratum :
new_y_breaks <- seq(from = fraction_missing, to = (100 + fraction_missing), by = 25)
new_y_labels <- seq(from = 0, to = 100, by = 25)

box_width <- 1/10
legend_title <- "clone type"
#legend_breaks <- levels(alv$cloneID)
```



```{r generate distinct colors for each alluvium and stratum}

# color_map_alv <- c("#FF6666", "#CC0000", "#CCFF99", "#339900", "#FFCC00", "#FF9933", "#9999FF", "#6600CC", "#66CCFF",  "#0000FF", "grey80") #Remy's color, old schemeB !!!\

color_map_alv <- c("lightcoral", "firebrick3", "darkseagreen3", "chartreuse4", "darkgoldenrod1", "darkgoldenrod3", "mediumpurple1", "mediumpurple4", "lightblue1", "darkcyan", "grey85")

names(color_map_alv) <- cloneOri

color_map_stratum <- c("grey70", "grey55")
names(color_map_stratum) <- c("present", "absent")

color_map <- c(color_map_alv, color_map_stratum)

alpha_map <- replicate(0.80, n = length(color_map))
names(alpha_map) <- names(color_map)
alpha_map[["absent"]] <- 1
alpha_map[["present"]] <- 1

```



```{r alluvial plot - artificial absence scale, fig.width=4, fig.height=4}

plotAlv <- function(alv, patient) {
  #legend_labels = alv$legend
  
  plt <- ggplot(alv,
                aes(x = Sample, y = Freq, 
                    stratum = Status, alluvium = cloneID)) +
  # set the geom flow and stratum
    geom_flow(aes(fill = cloneOri, alpha = cloneOri),
              na.rm = F, 
              #colour = "white", # --> include for Rémy oldScheme2 !!!
              aes.bind = "flows", width = 1/32) +
    geom_stratum(aes(fill = Status), 
                 na.rm = F, width = 1/8) +
  # set the text:
    geom_text(aes(label = stratum_text), stat = "stratum", size = 3.5, angle = 90) +
  # set the x and y axis
    scale_x_discrete(limits = levels(alv$Sample), expand = c(0,0)) +
    scale_y_continuous(breaks = new_y_breaks, labels = new_y_labels, expand = c(0,0)) +
    xlab("") +
    ylab("") +
    ggtitle(patient) +
    # set the colors manually: 
    scale_fill_manual(values = color_map, 
                      name = legend_title,
                      breaks = levels(alv$cloneOri),
                      guide = guide_legend(title.position = "top",
                                           ncol = 3)) + 
    scale_alpha_manual(values = alpha_map, name = legend_title, guide = "none") + 
    # theme: 
    theme(legend.position = "none", # none
          axis.ticks.x = element_blank(),
          axis.text.x = element_text(size = 14, face = "bold"),
          #axis.text.y = element_text(hjust = 0.7),
          #axis.title.y = element_text(size = 16, face = "bold"),
          plot.title = element_text(size = 18, colour = "blue", face = "bold", hjust = 0.5),
          panel.background = element_blank(),
          panel.grid.major.y = element_line(colour = "black", size = 0.5, linetype = "dotted"),
          panel.grid.minor = element_blank()
         )
  return(plt)

}

AlvMel.pl <- plotAlv(AlvMel, "4 pooled MelNeoTIL: 14MH, 13LN, 13P4, 1E18") + 
#scale_x_discrete(labels = c("B0", "T0", "ACTP", "B30", "T30"))
  ylab("Clone fraction") +
  theme(axis.text.y = element_text(size = 14),
        axis.title.y = element_text(size = 16, face = "bold"))
AlvMel.pl

AlvLung.pl <- plotAlv(AlvLung, "2 pooled LungNeoTIL: 1EDA, 1HU3") + 
  #scale_x_discrete(labels = c("B0", "T0", "ACTP", "B30", "T30")) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
AlvLung.pl

# Get common legend for all patients:
legend <- get_legend(AlvMel.pl +
                     guides(fill = guide_legend(title.position = "top", ncol = 3, reverse = FALSE)) + # number of legend columns
                     theme(legend.position = "bottom",
                           legend.title = element_text(size = 16),
                           legend.text = element_text(size = 14)
                          )
                    )

```


```{r plot, fig.width=12, fig.height=9}

pdf(paste0("new_4Mel.2Lung.NeoTIL", "_bulkTCR_combined.alluvial.plot_clone.evolution_from.5timepoints_20230605.pdf"), width = 12, height = 9)
fig <- plot_grid(AlvMel.pl, AlvLung.pl, 
                 align = c("vh"), ncol = 2)
#fig_legend
fig_legend <- plot_grid(fig, legend, nrow = 2, rel_heights = c(1.5,1))

annotate_figure(fig_legend, 
                top = text_grob("
                Mel/Lung.NeoTIL clone evolution in B0,T0,ACTP,B30,T30 bulkTCR
                                ", 
                                color = "black", face = "bold", size = 24),
                bottom = text_grob("present: clones with > 1 read      absent: clones with =< 1 read",
                                   color = "black", face = "bold", size = 16)
                )
dev.off()


```


